sonar.projectKey=android-app
sonar.exclusions=**/build/**,**/*.xml,**/*.png,**/*.jpg
sonar.java.source=17
sonar.coverage.jacoco.xmlReportPaths=app/build/reports/coverage/test/debug/report.xml,app/build/reports/coverage/unit/debug/report.xml
sonar.coverage.exclusions=\
  **/data/repository/impl/**,\
  **/data/local/**,\
  **/data/remote/**,\
  **/data/network/**,\
  **/di/**,\
  **/domain/model/**,\
  **/presentation/**
